Made settings filename into a parameter.
Added missing depends

diff --git a/bin/rad-loci b/bin/rad-loci
--- a/bin/rad-loci
+++ b/bin/rad-loci
@@ -55,6 +55,12 @@
 ## SETTINGS ##
 ##############
 
+if [ $# -ne 1 ]; then
+	echo "Usage: rad-loci SETTINGS.conf"
+	exit 1
+fi
+SETTINGSFILE=$1
+
 ## load settings ##
 # defaults
 DEFSETTINGS=$(dirname $0)/../share/rad-loci/settings.default
@@ -63,15 +69,16 @@ if [ -f $DEFSETTINGS ]; then
 else
 	echo "ERROR: Unable to locate default settings file"
 	echo "       It should be at: $DEFSETTINGS"
-	exit 1
+	exit 2
 fi
 
 # local override
-if [ -f settings.conf ]; then
-	source settings.conf
+if [ -f $SETTINGSFILE ]; then
+	source $SETTINGSFILE
 else
-	echo "WARNING: Unable to find local settings file"
-	echo "         run 'rad-loci-settings' to create one"
+	echo "ERROR: Unable to find local settings file"
+	echo "       run 'rad-loci-settings SETTINGS.conf' to create one"
+	exit 3
 fi
 
 ## Auto correct settings vars ##
diff --git a/bin/rad-loci-settings b/bin/rad-loci-settings
--- a/bin/rad-loci-settings
+++ b/bin/rad-loci-settings
@@ -2,16 +2,27 @@
 
 # creates a new settings file in the current working directory
 
-if [ -f settings.conf ]; then
-	echo "ERROR: settings.conf already exists"
+if [ $# -ne 1 ]; then
+	echo "Usage: rad-loci-settings SETTINGSFILE.conf"
 	exit 1
+fi
+
+OUTFILE=$1
+
+# check it doesn't exist
+if [ -f $OUTFILE ]; then
+	echo "ERROR: '$OUTFILE' already exists"
+	exit 2
 else
+	# make sure sample exists
 	SAMPSETTINGS=$(dirname $0)/../share/rad-loci/settings.sample
 	if [ ! -f $SAMPSETTINGS ]; then
 		echo "ERROR: unable to find sample settings file"
-		exit 2
+		exit 3
 	fi
-	cat $SAMPSETTINGS > settings.conf
-	echo "Created settings.conf"
+
+	# create settings file
+	cat $SAMPSETTINGS > $OUTFILE
+	echo "Created $OUTFILE"
 fi
 
